  asterisk:
    image: andrius/asterisk:latest
    restart: always
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    ports:
      - "5061:5060/udp" # Puerto externo para tu Softphone
      - "5061:5060/tcp"
      - "20000-20050:20000-20050/udp" # Rango reducido para Asterisk
    volumes:
      - ./config/pjsip.conf:/etc/asterisk/pjsip.conf
      - ./config/extensions.conf:/etc/asterisk/extensions.conf
      - ./config/rtp.conf:/etc/asterisk/rtp.conf
    environment:
      - ASTERISK_UID=1000
      - ASTERISK_GID=1000